name = "MORFERegistry"
uuid = "26dcb13d-7dbe-47af-94e6-00b434554957"
repo = "git@github.com:FlorianTuschner/MORFERegistry.git"
description = "Private registry for MORFE"

[packages]
1d4622c9-196a-4501-8c0e-eb226f4bd3c4 = { name = "MORFEFerrite", path = "M/MORFEFerrite" }

